### ISSUE TITLE
BlogController error

### ISSUE THREAD

**Issue by prodigital-design** [writingink/wink#174] opened 2019-05-08 08:25 UTC
when specifying 

Route::get('/', 'BlogController@index');
Route::get('/{tag}/{slug}', 'BlogController@post'); error appears

![image](https://user-images.githubusercontent.com/45261338/57360641-4e4f8700-7183-11e9-92f4-1bf09a295185.png)

**Comment by technodesign-dn** [comment] 2019-05-08 14:48
Is there a "wink" with a customized blog?

**Comment by technodesign-dn** [comment] 2019-05-08 15:13
> You've got to create a controller yourself https://laravel.com/docs/5.8/controllers.

Is there a "wink" with a customized blog?

**Comment by lucasdcrk** [comment] 2019-05-26 12:33
Duplicate of #175

**Closed** 2020-05-14 19:23 UTC
